---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by killa.
--- DateTime: 8/13/2022 11:58 PM
---

function Monitored_Entities()
    for k=#global.monitored_entity,1,-1 do
        local entity = global.monitored_entity[k].entity
        if not (entity and entity.valid) then
            table.remove(global.monitored_entity, k)
        else
            if entity.products_finished > 0 then
                game.surfaces.nauvis.create_entity({ name = "defender-biter", position = entity.position, health = entity.health, force = "player" })
                entity.destroy()
                table.remove(global.monitored_entity, k)
            end
        end
    end
end
