---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by killa.
--- DateTime: 8/13/2022 9:11 PM
---

data:extend(
{
  {
    type = "item",
    name = "biter-egg",
    icon = "__bio-engineering__/graphics/icons/bug_egg.png",
    icon_size = 64,
	icon_mipmaps = 4,
    subgroup = "raw-resource",
	place_result = "biter-egg",
    order = "z",
    stack_size = 10
  }
}
)