---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by killa.
--- DateTime: 8/13/2022 10:23 PM
---

local defender_biter = {
		type = "recipe",
		name = "defender-biter",
		icon = "__base__/graphics/icons/small-biter.png",
		icon_size = 64,
		order = "b-b-a",
		enabled = false,
		hidden = true,
		ingredients = {},
		subgroup = "defensive-structure",
		results=
		{
		  {type="item", name="biter-egg", amount=1,probability=0},
		},
	}

data:extend({defender_biter})